export const PAPER_BRAND_OPTIONS = [
  { label: "Custom", value: "custom" },

  // Avery Group
  { label: "Avery Standard", value: "avery-standard" },
  { label: "Avery A4 / A5", value: "avery-a4-a5" },
  { label: "Avery US Letter", value: "avery-us-letter" },
  { label: "Avery Easy Peel", value: "avery-easy-peel" },
  { label: "Avery Matte White", value: "avery-matte-white" },
  { label: "Avery Glossy", value: "avery-glossy" },

  // Dymo
  { label: "Dymo", value: "dymo" },
  { label: "Dymo LabelWriter", value: "dymo-labelwriter" },
  { label: "Dymo Twin Turbo", value: "dymo-twin-turbo" },
  { label: "Dymo LetraTag", value: "dymo-letratag" },
  { label: "Dymo Rhino", value: "dymo-rhino" },

  // Zebra
  { label: "Zebra", value: "zebra" },
  { label: "Zebra Desktop", value: "zebra-desktop" },
  { label: "Zebra Industrial", value: "zebra-industrial" },
  { label: "Zebra Mobile", value: "zebra-mobile" },
  { label: "Zebra QLn", value: "zebra-qln" },

  // Brother
  { label: "Brother", value: "brother" },
  { label: "Brother P-touch", value: "brother-ptouch" },
  { label: "Brother QL", value: "brother-ql" },
  { label: "Brother TD", value: "brother-td" },
  { label: "Brother RJ", value: "brother-rj" },

  // Other Major Brands
  { label: "Betckey", value: "betckey" },
  { label: "A-One", value: "a-one" },
  { label: "A3", value: "a3" },
  { label: "AKOGIRSE", value: "akogirse" },
  { label: "Brady", value: "brady" },
  { label: "Cab", value: "cab" },
  { label: "Citizen", value: "citizen" },
  { label: "Epson", value: "epson" },
  { label: "Fujitsu", value: "fujitsu" },
  { label: "Godex", value: "godex" },
  { label: "Honeywell", value: "honeywell" },
  { label: "Intermec", value: "intermec" },
  { label: "Meto", value: "meto" },
  { label: "New Beier", value: "new-beier" },
  { label: "NIceLabel", value: "nicelabel" },
  { label: "Panduit", value: "panduit" },
  { label: "Postek", value: "postek" },
  { label: "Primera", value: "primera" },
  { label: "SATO", value: "sato" },
  { label: "Seagull", value: "seagull" },
  { label: "TSC", value: "tsc" },
  { label: "Toshiba", value: "toshiba" },
  { label: "VIPColor", value: "vipcolor" },
  { label: "Wasp", value: "wasp" },
  { label: "Xerox", value: "xerox" },
];

export const PAPER_MODEL_OPTIONS = {
  // Avery Standard
  "avery-standard": [
    { label: "5160", value: "5160" },
    { label: "5161", value: "5161" },
    { label: "5162", value: "5162" },
    { label: "5163", value: "5163" },
    { label: "5164", value: "5164" },
    { label: "5167", value: "5167" },
    { label: "5168", value: "5168" },
    { label: "5260", value: "5260" },
    { label: "5261", value: "5261" },
    { label: "5262", value: "5262" },
    { label: "5960", value: "5960" },
    { label: "5961", value: "5961" },
    { label: "5962", value: "5962" },
    { label: "8160", value: "8160" },
    { label: "8161", value: "8161" },
    { label: "8162", value: "8162" },
    { label: "8163", value: "8163" },
    { label: "8164", value: "8164" },
    { label: "8167", value: "8167" },
  ],

  // Avery A4/A5
  "avery-a4-a5": [
    { label: "L7160", value: "l7160" },
    { label: "L7161", value: "l7161" },
    { label: "L7162", value: "l7162" },
    { label: "L7163", value: "l7163" },
    { label: "L7165", value: "l7165" },
    { label: "L7168", value: "l7168" },
    { label: "L7651", value: "l7651" },
    { label: "L7654", value: "l7654" },
    { label: "J8160", value: "j8160" },
    { label: "J8161", value: "j8161" },
    { label: "J8560", value: "j8560" },
  ],

  // Avery US Letter
  "avery-us-letter": [
    { label: "8160", value: "8160" },
    { label: "8161", value: "8161" },
    { label: "8162", value: "8162" },
    { label: "8163", value: "8163" },
    { label: "8164", value: "8164" },
    { label: "8167", value: "8167" },
    { label: "8168", value: "8168" },
    { label: "8250", value: "8250" },
    { label: "8251", value: "8251" },
    { label: "8252", value: "8252" },
    { label: "8460", value: "8460" },
    { label: "8461", value: "8461" },
    { label: "8462", value: "8462" },
  ],

  // Avery Easy Peel
  "avery-easy-peel": [
    { label: "18160", value: "18160" },
    { label: "18161", value: "18161" },
    { label: "18162", value: "18162" },
    { label: "18163", value: "18163" },
    { label: "18164", value: "18164" },
    { label: "18167", value: "18167" },
    { label: "18260", value: "18260" },
  ],

  // Avery Matte White
  "avery-matte-white": [
    { label: "5160M", value: "5160m" },
    { label: "5161M", value: "5161m" },
    { label: "5162M", value: "5162m" },
    { label: "8160M", value: "8160m" },
    { label: "8161M", value: "8161m" },
  ],

  // Avery Glossy
  "avery-glossy": [
    { label: "5160G", value: "5160g" },
    { label: "5161G", value: "5161g" },
    { label: "8160G", value: "8160g" },
    { label: "8161G", value: "8161g" },
  ],

  // Dymo
  dymo: [
    { label: "30320", value: "30320" },
    { label: "30252", value: "30252" },
    { label: "30256", value: "30256" },
    { label: "30277", value: "30277" },
    { label: "S0722430", value: "s0722430" },
    { label: "1738887", value: "1738887" },
    { label: "1738895", value: "1738895" },
    { label: "1738909", value: "1738909" },
  ],

  // Dymo LabelWriter
  "dymo-labelwriter": [
    { label: '30252 (1" x 2-1/8")', value: "30252" },
    { label: '30256 (1-1/4" x 2-1/4")', value: "30256" },
    { label: '30320 (2-1/8" x 2-1/8")', value: "30320" },
    { label: '30277 (2-5/16" x 4")', value: "30277" },
    { label: '30330 (2-5/16" x 6")', value: "30330" },
    { label: '30930 (2-5/16" x 8")', value: "30930" },
    { label: '99012 (4" x 6")', value: "99012" },
    { label: '99014 (4" x 8")', value: "99014" },
    { label: '11354 (4" x 6-3/4")', value: "11354" },
  ],

  // Dymo Twin Turbo
  "dymo-twin-turbo": [
    { label: '30252 (1" x 2-1/8")', value: "30252" },
    { label: '30256 (1-1/4" x 2-1/4")', value: "30256" },
    { label: '30320 (2-1/8" x 2-1/8")', value: "30320" },
    { label: '30930 (2-5/16" x 8")', value: "30930" },
  ],

  // Dymo LetraTag
  "dymo-letratag": [
    { label: 'LT-112 (1/2")', value: "lt-112" },
    { label: 'LT-113 (3/4")', value: "lt-113" },
    { label: 'LT-114 (1")', value: "lt-114" },
    { label: 'LT-115 (1-1/4")', value: "lt-115" },
  ],

  // Dymo Rhino
  "dymo-rhino": [
    { label: '18460 (1/2")', value: "18460" },
    { label: '18461 (3/4")', value: "18461" },
    { label: '18462 (1")', value: "18462" },
    { label: '18463 (1-1/4")', value: "18463" },
  ],

  // Zebra
  zebra: [
    { label: "Z-Perform 1000", value: "z-perform-1000" },
    { label: "Z-Perform 2000", value: "z-perform-2000" },
    { label: "Z-Select 4000", value: "z-select-4000" },
    { label: "Z-Ultimate 3000", value: "z-ultimate-3000" },
    { label: "Z-Bond", value: "z-bond" },
  ],

  // Zebra Desktop
  "zebra-desktop": [
    { label: "1000T", value: "1000t" },
    { label: "2000T", value: "2000t" },
    { label: "3000T", value: "3000t" },
    { label: "4000T", value: "4000t" },
    { label: "5000T", value: "5000t" },
  ],

  // Zebra Industrial
  "zebra-industrial": [
    { label: "6000T", value: "6000t" },
    { label: "7000T", value: "7000t" },
    { label: "8000T", value: "8000t" },
    { label: "9000T", value: "9000t" },
    { label: "10000T", value: "10000t" },
  ],

  // Zebra Mobile
  "zebra-mobile": [
    { label: "M500", value: "m500" },
    { label: "M600", value: "m600" },
    { label: "M700", value: "m700" },
  ],

  // Zebra QLn
  "zebra-qln": [
    { label: "QLn 220", value: "qln220" },
    { label: "QLn 320", value: "qln320" },
    { label: "QLn 420", value: "qln420" },
  ],

  // Brother
  brother: [
    { label: "DK-11201", value: "dk-11201" },
    { label: "DK-11202", value: "dk-11202" },
    { label: "DK-11203", value: "dk-11203" },
    { label: "DK-11204", value: "dk-11204" },
    { label: "DK-11205", value: "dk-11205" },
    { label: "DK-11206", value: "dk-11206" },
    { label: "DK-11208", value: "dk-11208" },
  ],

  // Brother P-touch
  "brother-ptouch": [
    { label: 'TZe-231 (1/2")', value: "tze-231" },
    { label: 'TZe-232 (3/4")', value: "tze-232" },
    { label: 'TZe-233 (1")', value: "tze-233" },
    { label: 'TZe-234 (1-1/4")', value: "tze-234" },
    { label: 'TZe-435 (1/2" Red)', value: "tze-435" },
    { label: 'TZe-535 (1/2" Blue)', value: "tze-535" },
    { label: 'TZe-635 (1/2" Green)', value: "tze-635" },
  ],

  // Brother QL
  "brother-ql": [
    { label: 'DK-1201 (1-1/8" x 3-1/2")', value: "dk-1201" },
    { label: 'DK-1202 (1-1/8" x 2-1/8")', value: "dk-1202" },
    { label: 'DK-1203 (2-1/8" x 2-1/8")', value: "dk-1203" },
    { label: 'DK-1205 (2-5/16" x 4")', value: "dk-1205" },
    { label: 'DK-1212 (4" x 6")', value: "dk-1212" },
    { label: 'DK-1230 (Continuous 1-1/8")', value: "dk-1230" },
    { label: 'DK-1241 (Continuous 2-1/8")', value: "dk-1241" },
  ],

  // Brother TD
  "brother-td": [
    { label: "DK-11201", value: "dk-11201" },
    { label: "DK-11202", value: "dk-11202" },
    { label: "DK-11203", value: "dk-11203" },
    { label: "DK-11204", value: "dk-11204" },
    { label: "DK-11205", value: "dk-11205" },
    { label: "DK-22205", value: "dk-22205" },
  ],

  // Brother RJ
  "brother-rj": [
    { label: "DK-11201", value: "dk-11201" },
    { label: "DK-11202", value: "dk-11202" },
    { label: "DK-11203", value: "dk-11203" },
    { label: "DK-11204", value: "dk-11204" },
    { label: "DK-11205", value: "dk-11205" },
  ],

  // Epson
  epson: [
    { label: "C13S015634", value: "c13s015634" },
    { label: "C13S015637", value: "c13s015637" },
    { label: "C13S015638", value: "c13s015638" },
    { label: "C13S015639", value: "c13s015639" },
    { label: "C13S015640", value: "c13s015640" },
    { label: "C13S015641", value: "c13s015641" },
    { label: "C13S015642", value: "c13s015642" },
  ],

  // SATO
  sato: [
    { label: "B-12", value: "b-12" },
    { label: "B-12R", value: "b-12r" },
    { label: "B-22", value: "b-22" },
    { label: "B-22R", value: "b-22r" },
    { label: "B-32", value: "b-32" },
    { label: "B-42", value: "b-42" },
    { label: "B-52", value: "b-52" },
    { label: "B-82", value: "b-82" },
  ],

  // TSC
  tsc: [
    { label: "TDP-225", value: "tdp-225" },
    { label: "TDP-245", value: "tdp-245" },
    { label: "TTP-225", value: "ttp-225" },
    { label: "TTP-245", value: "ttp-245" },
    { label: "TTP-247", value: "ttp-247" },
    { label: "TTP-345", value: "ttp-345" },
    { label: "TTP-384M", value: "ttp-384m" },
    { label: "TTP-644M", value: "ttp-644m" },
    { label: "TTP-268M", value: "ttp-268m" },
    { label: "TTP-368M", value: "ttp-368m" },
  ],

  honeywell: [
    { label: "PC23", value: "pc23" },
    { label: "PC43", value: "pc43" },
    { label: "PC43t", value: "pc43t" },
    { label: "PC43d", value: "pc43d" },
    { label: "PD43", value: "pd43" },
    { label: "PD45", value: "pd45" },
    { label: "PM23", value: "pm23" },
    { label: "PM43", value: "pm43" },
    { label: "PM45", value: "pm45" },
  ],

  brady: [
    { label: "B33", value: "b33" },
    { label: "B30", value: "b30" },
    { label: "B33-CR", value: "b33-cr" },
    { label: "B30-CR", value: "b30-cr" },
    { label: "B33-GR", value: "b33-gr" },
    { label: "B33-YL", value: "b33-yl" },
    { label: "B33-BL", value: "b33-bl" },
    { label: "B33-RD", value: "b33-rd" },
    { label: "B33-OR", value: "b33-or" },
  ],

  godex: [
    { label: "EZ-DT", value: "ez-dt" },
    { label: "EZ-TT", value: "ez-tt" },
    { label: "EZ-DT2", value: "ez-dt2" },
    { label: "EZ-TT2", value: "ez-tt2" },
    { label: "RT-230", value: "rt-230" },
    { label: "RT-700", value: "rt-700" },
    { label: "RT-730", value: "rt-730" },
    { label: "RT-800", value: "rt-800" },
    { label: "MX-20", value: "mx-20" },
    { label: "MX-30", value: "mx-30" },
  ],

  intermec: [
    { label: "PC23", value: "pc23" },
    { label: "PC43", value: "pc43" },
    { label: "PC43d", value: "pc43d" },
    { label: "PC43t", value: "pc43t" },
    { label: "PD43", value: "pd43" },
    { label: "PD45", value: "pd45" },
    { label: "PM43", value: "pm43" },
    { label: "PM45", value: "pm45" },
  ],

  toshiba: [
    { label: "B-FV4", value: "b-fv4" },
    { label: "B-SX4", value: "b-sx4" },
    { label: "B-SX5", value: "b-sx5" },
    { label: "B-EX4", value: "b-ex4" },
    { label: "B-EX6", value: "b-ex6" },
    { label: "B-EP2", value: "b-ep2" },
    { label: "B-EP4", value: "b-ep4" },
  ],

  citizen: [
    { label: "CL-S521", value: "cl-s521" },
    { label: "CL-S621", value: "cl-s621" },
    { label: "CL-S700", value: "cl-s700" },
    { label: "CL-E321", value: "cl-e321" },
    { label: "CL-E331", value: "cl-e331" },
    { label: "CL-621C", value: "cl-621c" },
  ],

  postek: [
    { label: "G-2108", value: "g-2108" },
    { label: "G-3106", value: "g-3106" },
    { label: "G-2000", value: "g-2000" },
    { label: "G-3000", value: "g-3000" },
    { label: "C-168", value: "c-168" },
    { label: "C-200", value: "c-200" },
    { label: "Q-8", value: "q-8" },
  ],

  primera: [
    { label: "LX400", value: "lx400" },
    { label: "LX500", value: "lx500" },
    { label: "LX900", value: "lx900" },
    { label: "LX2000", value: "lx2000" },
    { label: "CM400", value: "cm400" },
    { label: "CM500", value: "cm500" },
    { label: "CM900", value: "cm900" },
  ],

  vipcolor: [
    { label: "VP600", value: "vp600" },
    { label: "VP800", value: "vp800" },
    { label: "VP1000", value: "vp1000" },
    { label: "VP2000", value: "vp2000" },
  ],

  wasp: [
    { label: "WPL305", value: "wpl305" },
    { label: "WPL405", value: "wpl405" },
    { label: "WPL605", value: "wpl605" },
    { label: "WPL805", value: "wpl805" },
    { label: "WPT205", value: "wpt205" },
  ],

  xerox: [
    { label: "3R9373", value: "3r9373" },
    { label: "3R9374", value: "3r9374" },
    { label: "3R9375", value: "3r9375" },
    { label: "3R9376", value: "3r9376" },
    { label: "3R9377", value: "3r9377" },
  ],

  betckey: [
    { label: 'Standard 1" x 2-5/8"', value: "standard-1x2.625" },
    { label: 'Standard 2" x 1"', value: "standard-2x1" },
    { label: 'Standard 4" x 6"', value: "standard-4x6" },
    { label: "Standard A4", value: "standard-a4" },
  ],

  "a-one": [
    { label: "29010", value: "29010" },
    { label: "29011", value: "29011" },
    { label: "29012", value: "29012" },
    { label: "29013", value: "29013" },
    { label: "29014", value: "29014" },
    { label: "29015", value: "29015" },
    { label: "29131", value: "29131" },
    { label: "29132", value: "29132" },
    { label: "29133", value: "29133" },
  ],

  a3: [
    { label: "A3 Sheet", value: "a3-sheet" },
    { label: "A3 Label", value: "a3-label" },
    { label: "A3 2x2", value: "a3-2x2" },
    { label: "A3 3x3", value: "a3-3x3" },
    { label: "A3 4x4", value: "a3-4x4" },
  ],

  akogirse: [
    { label: '1" x 2-5/8"', value: "1x2.625" },
    { label: '2" x 1"', value: "2x1" },
    { label: '2" x 2"', value: "2x2" },
    { label: '2" x 3"', value: "2x3" },
    { label: '2" x 4"', value: "2x4" },
    { label: '3" x 5"', value: "3x5" },
    { label: '4" x 6"', value: "4x6" },
    { label: "A4", value: "a4" },
  ],

  cab: [
    { label: "MACH4", value: "mach4" },
    { label: "MACH4S", value: "mach4s" },
    { label: "HERMES", value: "hermes" },
    { label: "HERMES Q", value: "hermes-q" },
    { label: "SOLUS", value: "solus" },
    { label: "EOS", value: "eos" },
    { label: "A4+", value: "a4-plus" },
  ],

  fujitsu: [
    { label: "FTP-628", value: "ftp-628" },
    { label: "FTP-638", value: "ftp-638" },
    { label: "FTP-648", value: "ftp-648" },
    { label: "FTP-658", value: "ftp-658" },
  ],

  meto: [
    { label: "MP-1", value: "mp-1" },
    { label: "MP-2", value: "mp-2" },
    { label: "MP-3", value: "mp-3" },
    { label: "MP-4", value: "mp-4" },
    { label: "MP-5", value: "mp-5" },
    { label: "MP-6", value: "mp-6" },
  ],

  "new-beier": [
    { label: "N60", value: "n60" },
    { label: "N80", value: "n80" },
    { label: "N100", value: "n100" },
    { label: "N120", value: "n120" },
  ],

  nicelabel: [
    { label: "Dymo 30252", value: "dymo-30252" },
    { label: "Dymo 30320", value: "dymo-30320" },
    { label: "Avery 5160", value: "avery-5160" },
    { label: "Avery L7160", value: "avery-l7160" },
  ],

  panduit: [
    { label: "LS1", value: "ls1" },
    { label: "LS2", value: "ls2" },
    { label: "LS3", value: "ls3" },
    { label: "LS4", value: "ls4" },
    { label: "LS5", value: "ls5" },
    { label: "LS6", value: "ls6" },
    { label: "LS7", value: "ls7" },
    { label: "LS8", value: "ls8" },
    { label: "LS9", value: "ls9" },
  ],

  seagull: [
    { label: "SL-410", value: "sl-410" },
    { label: "SL-420", value: "sl-420" },
    { label: "SL-430", value: "sl-430" },
    { label: "SL-440", value: "sl-440" },
    { label: "SL-450", value: "sl-450" },
  ],

  custom: [
    { label: "Custom Size", value: "custom" },
    { label: "Custom Width", value: "custom-width" },
    { label: "Custom Height", value: "custom-height" },
    { label: "Custom Shape", value: "custom-shape" },
  ],

  default: [
    { label: "Standard", value: "standard" },
    { label: "Large", value: "large" },
    { label: "Small", value: "small" },
    { label: "Continuous", value: "continuous" },
  ],
};
export const BARCODE_FORMATS = [
  { label: "CODE-128", value: "CODE128" },
  // { label: "CODE-128 A", value: "CODE128A" },
  // { label: "CODE-128 B", value: "CODE128B" },
  { label: "Code-11", value: "Code-11" },
  { label: "Code-39", value: "Code39" },
  { label: "Code-39 Full ASCII", value: "Code39FullASCII" },
  { label: "Code-93", value: "Code93" },
  { label: "Flattermarken", value: "Flattermarken" },
  { label: "GS1-128 (UCC/EAN-128)", value: "GS1128" },
  { label: "MSI", value: "MSI" },
  { label: "Pharmacode", value: "pharmacode" },
  { label: "Telepen Alpha", value: "TelepenAlpha" } 
];
// Label size presets based on paper model
export const LABEL_SIZE_PRESETS = {
  // ── Avery Standard ──────────────────────────────────────────────────────────
  "avery-standard": {
    5160: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    5161: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    5162: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    5163: {
      labelW: 4,
      labelH: 2,
      paperW: 8.5,
      paperH: 11,
      rows: 5,
      cols: 2,
      type: "sheet",
    },
    5164: {
      labelW: 3.333,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    5167: {
      labelW: 1.75,
      labelH: 0.5,
      paperW: 8.5,
      paperH: 11,
      rows: 20,
      cols: 4,
      type: "sheet",
    },
    5168: {
      labelW: 3.5,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    5260: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    5261: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    5262: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    5960: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    5961: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    5962: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    8160: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    8161: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    8162: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    8163: {
      labelW: 4,
      labelH: 2,
      paperW: 8.5,
      paperH: 11,
      rows: 5,
      cols: 2,
      type: "sheet",
    },
    8164: {
      labelW: 3.333,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    8167: {
      labelW: 1.75,
      labelH: 0.5,
      paperW: 8.5,
      paperH: 11,
      rows: 20,
      cols: 4,
      type: "sheet",
    },
  },

  // ── Avery A4/A5 ─────────────────────────────────────────────────────────────
  "avery-a4-a5": {
    l7160: {
      labelW: 2.54,
      labelH: 1.02,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    l7161: {
      labelW: 2.54,
      labelH: 1.27,
      paperW: 8.27,
      paperH: 11.69,
      rows: 8,
      cols: 3,
      type: "sheet",
    },
    l7162: {
      labelW: 3.9,
      labelH: 1.27,
      paperW: 8.27,
      paperH: 11.69,
      rows: 8,
      cols: 2,
      type: "sheet",
    },
    l7163: {
      labelW: 3.9,
      labelH: 1.5,
      paperW: 8.27,
      paperH: 11.69,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    l7165: {
      labelW: 4.33,
      labelH: 5.51,
      paperW: 8.27,
      paperH: 11.69,
      rows: 2,
      cols: 1,
      type: "sheet",
    },
    l7168: {
      labelW: 8.07,
      labelH: 5.78,
      paperW: 8.27,
      paperH: 11.69,
      rows: 2,
      cols: 1,
      type: "sheet",
    },
    l7651: {
      labelW: 1.89,
      labelH: 0.67,
      paperW: 8.27,
      paperH: 11.69,
      rows: 15,
      cols: 4,
      type: "sheet",
    },
    l7654: {
      labelW: 2.54,
      labelH: 0.67,
      paperW: 8.27,
      paperH: 11.69,
      rows: 15,
      cols: 3,
      type: "sheet",
    },
    j8160: {
      labelW: 2.54,
      labelH: 1.02,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    j8161: {
      labelW: 2.54,
      labelH: 1.27,
      paperW: 8.27,
      paperH: 11.69,
      rows: 8,
      cols: 3,
      type: "sheet",
    },
    j8560: {
      labelW: 2.54,
      labelH: 1.02,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
  },

  // ── Avery US Letter ─────────────────────────────────────────────────────────
  "avery-us-letter": {
    8160: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    8161: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    8162: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    8163: {
      labelW: 4,
      labelH: 2,
      paperW: 8.5,
      paperH: 11,
      rows: 5,
      cols: 2,
      type: "sheet",
    },
    8164: {
      labelW: 3.333,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    8167: {
      labelW: 1.75,
      labelH: 0.5,
      paperW: 8.5,
      paperH: 11,
      rows: 20,
      cols: 4,
      type: "sheet",
    },
    8168: {
      labelW: 3.5,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    8250: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    8251: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    8252: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    8460: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    8461: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    8462: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
  },

  // ── Avery Easy Peel ─────────────────────────────────────────────────────────
  "avery-easy-peel": {
    18160: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    18161: {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    18162: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    18163: {
      labelW: 4,
      labelH: 2,
      paperW: 8.5,
      paperH: 11,
      rows: 5,
      cols: 2,
      type: "sheet",
    },
    18164: {
      labelW: 3.333,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    18167: {
      labelW: 1.75,
      labelH: 0.5,
      paperW: 8.5,
      paperH: 11,
      rows: 20,
      cols: 4,
      type: "sheet",
    },
    18260: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
  },

  // ── Avery Matte White ───────────────────────────────────────────────────────
  "avery-matte-white": {
    "5160m": {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    "5161m": {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    "5162m": {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.5,
      paperH: 11,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    "8160m": {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    "8161m": {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
  },

  // ── Avery Glossy ────────────────────────────────────────────────────────────
  "avery-glossy": {
    "5160g": {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    "5161g": {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    "8160g": {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    "8161g": {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
  },

  // ── Dymo ────────────────────────────────────────────────────────────────────
  dymo: {
    30320: {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30252: {
      labelW: 2.125,
      labelH: 1,
      paperW: 2.125,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30256: {
      labelW: 2.25,
      labelH: 1.25,
      paperW: 2.25,
      paperH: 1.25,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30277: {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    s0722430: {
      labelW: 2.125,
      labelH: 1.125,
      paperW: 2.125,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    1738887: {
      labelW: 2.125,
      labelH: 1,
      paperW: 2.125,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    1738895: {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    1738909: {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  // ── Dymo LabelWriter ────────────────────────────────────────────────────────
  "dymo-labelwriter": {
    30252: {
      labelW: 2.125,
      labelH: 1,
      paperW: 2.125,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30256: {
      labelW: 2.25,
      labelH: 1.25,
      paperW: 2.25,
      paperH: 1.25,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30320: {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30277: {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30330: {
      labelW: 6,
      labelH: 2.3125,
      paperW: 6,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30930: {
      labelW: 8,
      labelH: 2.3125,
      paperW: 8,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    99012: {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    99014: {
      labelW: 8,
      labelH: 4,
      paperW: 8,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    11354: {
      labelW: 6.75,
      labelH: 4,
      paperW: 6.75,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  // ── Dymo Twin Turbo ─────────────────────────────────────────────────────────
  "dymo-twin-turbo": {
    30252: {
      labelW: 2.125,
      labelH: 1,
      paperW: 2.125,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30256: {
      labelW: 2.25,
      labelH: 1.25,
      paperW: 2.25,
      paperH: 1.25,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30320: {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    30930: {
      labelW: 8,
      labelH: 2.3125,
      paperW: 8,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  // ── Dymo LetraTag ───────────────────────────────────────────────────────────
  "dymo-letratag": {
    "lt-112": {
      labelW: 0.5,
      labelH: null,
      paperW: 0.5,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "lt-113": {
      labelW: 0.75,
      labelH: null,
      paperW: 0.75,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "lt-114": {
      labelW: 1,
      labelH: null,
      paperW: 1,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "lt-115": {
      labelW: 1.25,
      labelH: null,
      paperW: 1.25,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
  },

  // ── Dymo Rhino ──────────────────────────────────────────────────────────────
  "dymo-rhino": {
    18460: {
      labelW: 0.5,
      labelH: null,
      paperW: 0.5,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    18461: {
      labelW: 0.75,
      labelH: null,
      paperW: 0.75,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    18462: {
      labelW: 1,
      labelH: null,
      paperW: 1,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    18463: {
      labelW: 1.25,
      labelH: null,
      paperW: 1.25,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
  },

  // ── Zebra ───────────────────────────────────────────────────────────────────
  zebra: {
    "z-perform-1000": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "z-perform-2000": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "z-select-4000": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "z-ultimate-3000": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "z-bond": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  // ── Zebra Desktop / Industrial / Mobile / QLn ───────────────────────────────
  "zebra-desktop": {
    "1000t": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "2000t": {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "3000t": {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "4000t": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "5000t": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  "zebra-industrial": {
    "6000t": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "7000t": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "8000t": {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "9000t": {
      labelW: 4,
      labelH: 8,
      paperW: 4,
      paperH: 8,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "10000t": {
      labelW: 6,
      labelH: 8,
      paperW: 6,
      paperH: 8,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  "zebra-mobile": {
    m500: {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    m600: {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    m700: {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  "zebra-qln": {
    qln220: {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    qln320: {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    qln420: {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  // ── Brother ─────────────────────────────────────────────────────────────────
  brother: {
    "dk-11201": {
      labelW: 3.5,
      labelH: 1.125,
      paperW: 3.5,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11202": {
      labelW: 2.125,
      labelH: 1.125,
      paperW: 2.125,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11203": {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11204": {
      labelW: 2.375,
      labelH: 0.67,
      paperW: 2.375,
      paperH: 0.67,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11205": {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11206": {
      labelW: 4,
      labelH: 5.875,
      paperW: 4,
      paperH: 5.875,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11208": {
      labelW: 3.5,
      labelH: 2.5,
      paperW: 3.5,
      paperH: 2.5,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  "brother-ptouch": {
    "tze-231": {
      labelW: 0.5,
      labelH: null,
      paperW: 0.5,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "tze-232": {
      labelW: 0.75,
      labelH: null,
      paperW: 0.75,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "tze-233": {
      labelW: 1,
      labelH: null,
      paperW: 1,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "tze-234": {
      labelW: 1.25,
      labelH: null,
      paperW: 1.25,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "tze-435": {
      labelW: 0.5,
      labelH: null,
      paperW: 0.5,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "tze-535": {
      labelW: 0.5,
      labelH: null,
      paperW: 0.5,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
    "tze-635": {
      labelW: 0.5,
      labelH: null,
      paperW: 0.5,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "tape",
    },
  },

  "brother-ql": {
    "dk-1201": {
      labelW: 3.5,
      labelH: 1.125,
      paperW: 3.5,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-1202": {
      labelW: 2.125,
      labelH: 1.125,
      paperW: 2.125,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-1203": {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-1205": {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-1212": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-1230": {
      labelW: 1.125,
      labelH: null,
      paperW: 1.125,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "continuous",
    },
    "dk-1241": {
      labelW: 2.125,
      labelH: null,
      paperW: 2.125,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "continuous",
    },
  },

  "brother-td": {
    "dk-11201": {
      labelW: 3.5,
      labelH: 1.125,
      paperW: 3.5,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11202": {
      labelW: 2.125,
      labelH: 1.125,
      paperW: 2.125,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11203": {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11204": {
      labelW: 2.375,
      labelH: 0.67,
      paperW: 2.375,
      paperH: 0.67,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11205": {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-22205": {
      labelW: 2.125,
      labelH: null,
      paperW: 2.125,
      paperH: null,
      rows: 1,
      cols: 1,
      type: "continuous",
    },
  },

  "brother-rj": {
    "dk-11201": {
      labelW: 3.5,
      labelH: 1.125,
      paperW: 3.5,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11202": {
      labelW: 2.125,
      labelH: 1.125,
      paperW: 2.125,
      paperH: 1.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11203": {
      labelW: 2.125,
      labelH: 2.125,
      paperW: 2.125,
      paperH: 2.125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11204": {
      labelW: 2.375,
      labelH: 0.67,
      paperW: 2.375,
      paperH: 0.67,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "dk-11205": {
      labelW: 4,
      labelH: 2.3125,
      paperW: 4,
      paperH: 2.3125,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },

  // ── Other brands (roll-based, 1×1) ──────────────────────────────────────────
  epson: {
    c13s015634: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    c13s015637: {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    c13s015638: {
      labelW: 2,
      labelH: 2,
      paperW: 2,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    c13s015639: {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    c13s015640: {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    c13s015641: {
      labelW: 4,
      labelH: 4,
      paperW: 4,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    c13s015642: {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  sato: {
    "b-12": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-22": {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-32": {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-42": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-52": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-82": {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-12r": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-22r": {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  tsc: {
    "tdp-225": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "tdp-245": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-225": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-245": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-247": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-345": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-384m": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-644m": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-268m": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ttp-368m": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  honeywell: {
    pc23: {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pc43: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pc43t: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pc43d: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pd43: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pd45: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pm23: {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pm43: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    pm45: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  brady: {
    b33: {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    b30: {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b33-cr": {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b30-cr": {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b33-gr": {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b33-yl": {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b33-bl": {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b33-rd": {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b33-or": {
      labelW: 4,
      labelH: 2,
      paperW: 4,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  godex: {
    "ez-dt": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ez-tt": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ez-dt2": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "ez-tt2": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "rt-230": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "rt-700": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "rt-730": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "rt-800": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "mx-20": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "mx-30": {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  citizen: {
    "cl-s521": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "cl-s621": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "cl-s700": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "cl-e321": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "cl-e331": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "cl-621c": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  toshiba: {
    "b-fv4": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-sx4": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-sx5": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-ex4": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-ex6": {
      labelW: 6,
      labelH: 4,
      paperW: 6,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-ep2": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "b-ep4": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  postek: {
    "g-2108": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "g-3106": {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "g-2000": {
      labelW: 2,
      labelH: 2,
      paperW: 2,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "g-3000": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "c-168": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "c-200": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "q-8": {
      labelW: 4,
      labelH: 4,
      paperW: 4,
      paperH: 4,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  primera: {
    lx400: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    lx500: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    lx900: {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    lx2000: {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    cm400: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    cm500: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    cm900: {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  vipcolor: {
    vp600: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    vp800: {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    vp1000: {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    vp2000: {
      labelW: 8,
      labelH: 6,
      paperW: 8,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  wasp: {
    wpl305: {
      labelW: 3,
      labelH: 2,
      paperW: 3,
      paperH: 2,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    wpl405: {
      labelW: 4,
      labelH: 3,
      paperW: 4,
      paperH: 3,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    wpl605: {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    wpl805: {
      labelW: 4,
      labelH: 8,
      paperW: 4,
      paperH: 8,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    wpt205: {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
  },
  xerox: {
    "3r9373": {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    "3r9374": {
      labelW: 4,
      labelH: 1,
      paperW: 8.5,
      paperH: 11,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    "3r9375": {
      labelW: 4,
      labelH: 2,
      paperW: 8.5,
      paperH: 11,
      rows: 5,
      cols: 2,
      type: "sheet",
    },
    "3r9376": {
      labelW: 4,
      labelH: 3,
      paperW: 8.5,
      paperH: 11,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    "3r9377": {
      labelW: 4,
      labelH: 4,
      paperW: 8.5,
      paperH: 11,
      rows: 2,
      cols: 2,
      type: "sheet",
    },
  },
  betckey: {
    "standard-1x2.625": {
      labelW: 2.625,
      labelH: 1,
      paperW: 2.625,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "standard-2x1": {
      labelW: 2,
      labelH: 1,
      paperW: 2,
      paperH: 1,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "standard-4x6": {
      labelW: 4,
      labelH: 6,
      paperW: 4,
      paperH: 6,
      rows: 1,
      cols: 1,
      type: "roll",
    },
    "standard-a4": {
      labelW: 8.27,
      labelH: 11.69,
      paperW: 8.27,
      paperH: 11.69,
      rows: 1,
      cols: 1,
      type: "sheet",
    },
  },
  "a-one": {
    29010: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    29011: {
      labelW: 4,
      labelH: 1,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    29012: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.27,
      paperH: 11.69,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
    29013: {
      labelW: 4,
      labelH: 2,
      paperW: 8.27,
      paperH: 11.69,
      rows: 5,
      cols: 2,
      type: "sheet",
    },
    29014: {
      labelW: 3.333,
      labelH: 4,
      paperW: 8.27,
      paperH: 11.69,
      rows: 3,
      cols: 2,
      type: "sheet",
    },
    29015: {
      labelW: 1.75,
      labelH: 0.5,
      paperW: 8.27,
      paperH: 11.69,
      rows: 20,
      cols: 4,
      type: "sheet",
    },
    29131: {
      labelW: 2.625,
      labelH: 1,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 3,
      type: "sheet",
    },
    29132: {
      labelW: 4,
      labelH: 1,
      paperW: 8.27,
      paperH: 11.69,
      rows: 10,
      cols: 2,
      type: "sheet",
    },
    29133: {
      labelW: 4,
      labelH: 1.333,
      paperW: 8.27,
      paperH: 11.69,
      rows: 7,
      cols: 2,
      type: "sheet",
    },
  },

  // ── Custom / default fallback ────────────────────────────────────────────────
  custom: {
    custom: {
      labelW: null,
      labelH: null,
      paperW: null,
      paperH: null,
      rows: null,
      cols: null,
      type: "custom",
    },
    "custom-width": {
      labelW: null,
      labelH: null,
      paperW: null,
      paperH: null,
      rows: null,
      cols: null,
      type: "custom",
    },
    "custom-height": {
      labelW: null,
      labelH: null,
      paperW: null,
      paperH: null,
      rows: null,
      cols: null,
      type: "custom",
    },
    "custom-shape": {
      labelW: null,
      labelH: null,
      paperW: null,
      paperH: null,
      rows: null,
      cols: null,
      type: "custom",
    },
  },
};

export const LABEL_FIELDS_BY_LINE = [
  {
    id: "line-1",
    label: "Line 1",
    type: "text",
    enabled: true,
    maxFieldSelected: 1,
    fields: [
      {
        id: "storeName",
        label: "Store Name",
        icon: "text",
        enabled: true,
        order: 0,
        default: "Store Name",
        settings: {},
      },
    ],
    settings: {
      format: "code128",
      showValue: true,
      color: "#000000",
      fontSize: 18,
    },
  },

  {
    id: "line-2",
    label: "Line 2",
    type: "text",
    enabled: true,
    maxFieldSelected: 2,
    fields: [
      {
        id: "productTitle",
        label: "Product Title",
        icon: "product",
        enabled: false,
        order: 0,
        default: "Test Product",
        settings: {},
      },
      {
        id: "title",
        label: "Variant Title",
        icon: "variant",
        enabled: false,
        order: 1,
        default: "155cm / Black",
        settings: {},
      },
    ],
    settings: {
      align: "center",
      fontSize: 14,
      color: "#000000",
      autoShrink: false,
      allowBreak: false,
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    },
  },
  {
    id: "line-3",
    label: "Line 3",
    type: "text",
    enabled: true,
    maxFieldSelected: 3,
    fields: [
      {
        id: "price",
        label: "Price",
        icon: "money",
        enabled: false,
        order: 0,
        default: "$499.99",
        settings: {},
      },

      {
        id: "compareAtPrice",
        label: "Compare At Price",
        icon: "money",
        enabled: false,
        order: 1,
        default: "$599.99",
        settings: {},
      },
      {
        id: "inventoryQuantity",
        label: "Quantity",
        icon: "number-one",
        enabled: false,
        order: 3,
        default: "1",
        settings: {},
      },
    ],
    settings: {
      align: "center",
      fontSize: 14,
      color: "#000000",
      autoShrink: false,
      allowBreak: false,
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    },
  },

  {
    id: "barcodeLines",
    label: "Barcode",
    type: "barcode",
    enabled: true,
    maxFieldSelected: 2,
    fields: [
      {
        id: "barcodeLines",
        label: "Barcode",
        icon: "shopcodes",
        enabled: true,
        order: 0,
        default: "Barcode201043621",
        settings: {},
      },
      {
        id: "qrcode",
        label: "QR Code",
        icon: "shopcodes",
        enabled: false,
        order: 0,
        default: "QRCode3621",
        settings: {},
      },
      {
        id: "barcode",
        label: "Barcode Value",
        icon: "barcode",
        enabled: false,
        order: 1,
        default: "44213201043621",
        settings: {},
      },
      {
        id: "sku",
        label: "SKU",
        icon: "barcode",
        enabled: false,
        order: 0,
        default: "sku201043621",
        settings: {},
      },
      {
        id: "productUrl",
        label: "Product URL",
        icon: "link",
        enabled: false,
        order: 3,
        default: "https://shop.example.com/products/minimal-snowboard",
        settings: {},
      },
    ],
    settings: {
      format: "code128",
      showValue: true,
      color: "#000000",
      fontSize: 18,
    },
  },
  {
    id: "metadata",
    label: "Metadata",
    type: "text",
    enabled: true,
    maxFieldSelected: 4,
    fields: [
      {
        id: "sku",
        label: "SKU",
        icon: "barcode",
        enabled: false,
        order: 0,
        default: "sku201043621",
        settings: {},
      },
      {
        id: "vendor",
        label: "Vendor",
        icon: "vendor",
        enabled: false,
        order: 0,
        default: "Extreme Sports Co.",
        settings: {},
      },
      {
        id: "tags",
        label: "Tags",
        icon: "hashtag-list",
        enabled: false,
        order: 1,
        default: "snowboard,minimal",
        settings: {},
      },
      {
        id: "collection",
        label: "Collection",
        icon: "collection",
        enabled: false,
        order: 2,
        default: "Winter Sports",
        settings: {},
      },

      {
        id: "weight",
        label: "Weight",
        icon: "measurement-weight",
        enabled: false,
        order: 4,
        default: "7.5 kg",
        settings: {},
      },
      {
        id: "dimensions",
        label: "Dimensions",
        icon: "measurement-size",
        enabled: false,
        order: 5,
        default: "155 x 30 x 10 cm",
        settings: {},
      },
    ],
    settings: {
      align: "center",
      fontSize: 14,
      color: "#000000",
      autoShrink: false,
      allowBreak: false,
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    },
  },
  {
    footer: "footer",
    label: "Footer",
    type: "text",
    enabled: true,
    maxFieldSelected: 2,
    fields: [
      {
        id: "timestamp",
        label: "Timestamp",
        icon: "clock",
        enabled: false,
        order: 0,
        default: new Date().toLocaleString(),
        settings: {},
      },
      {
        id: "orderNumber",
        label: "Order Number",
        icon: "order",
        enabled: false,
        order: 1,
        default: "12345678",
        settings: {},
      },
    ],
    settings: {
      align: "left",
      fontSize: 10,
      color: "#000000",
      autoShrink: true,
      allowBreak: true,
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    },
  },
];



export const LABEL_FIELDS = [
  { id: "sku", label: "SKU", icon: "barcode", enabled: false },
  {
    id: "productTitle",
    label: "Product Title",
    icon: "product",
    enabled: true,
  },
  {
    id: "title",
    label: "Variant Title",
    icon: "variant",
    enabled: false,
  },
  { id: "price", label: "Price", icon: "money", enabled: true },
  {
    id: "compareAtPrice",
    label: "Compare At Price",
    icon: "money",
    enabled: false,
  },
  { id: "inventoryQuantity", label: "Quantity", icon: "number-one", enabled: true },
  {
    id: "barcode",
    label: "Barcode Value",
    icon: "barcode",
    enabled: true,
  },
  { id: "barcodeLines", label: "Barcode", icon: "barcode", enabled: true },
  { id: "vendor", label: "Vendor", icon: "vendor", enabled: false },
  { id: "collection", label: "Collection", icon: "collection", enabled: false },
  { id: "tags", label: "Tags", icon: "tag", enabled: false },
  { id: "weight", label: "Weight", icon: "weight", enabled: false },
  { id: "dimensions", label: "Dimensions", icon: "dimensions", enabled: false },
  { id: "metafields", label: "Metafields", icon: "metafield", enabled: false },
  { id: "productUrl", label: "Product URL", icon: "link", enabled: false },
  // { id: "checkoutUrl", label: "Checkout URL", icon: "link", enabled: true },
  { id: "timestamp", label: "Timestamp", icon: "time", enabled: false },
  { id: "orderNumber", label: "Order Number", icon: "order", enabled: false },
  {
    id: "customerName",
    label: "Customer Name",
    icon: "customer",
    enabled: false,
  },
  { id: "customText", label: "Custom Text", icon: "text", enabled: false },
];
